[package]
name = "cloakrs-tracing"
description = "tracing integration for redacting PII with cloakrs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/cloakrs-tracing"
readme = "../../README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
cloakrs-core = { path = "../cloakrs-core", version = "0.3.0" }
tracing.workspace = true
tracing-subscriber.workspace = true
